In [1]:
import numpy as np 
import pandas as pd 
import matplotlib as plt 
import seaborn as sns

In [29]:
path = "D:/Data Science/Git Hub/Pak-Spam-Guard/expanded_pakistan_spam_dataset_10k.csv"
spamdf = pd.read_csv(path)
spamdf.head ()

,id,text,spam,scam_type,language,url_present,url_harmful
0,1,"Congratulations! You have won PKR 500,000 in H...",spam,lottery_prize_scam,english,no,NaN
1,2,"Dear Customer, your Meezan Bank account has be...",spam,bank_phishing,english,yes,yes
2,3,BISP khuskhbri! Aap ko 25000 rupay ki qist mil...,spam,BISP_government_scam,roman_urdu,no,NaN
3,4,Your JazzCash account will be blocked. Please ...,spam,mobile_wallet_phishing,english,yes,yes
4,5,Salam! Mujhe ek emergency hai. Mera phone khat...,spam,easyload_scam,roman_urdu,no,NaN

In [30]:
spamdf.isnull().sum()
spamdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 9300 entries, 0 to 9299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9300 non-null   int64
 1   text         9300 non-null   str
 2   spam         9300 non-null   str
 3   scam_type    9300 non-null   str
 4   language     9300 non-null   str
 5   url_present  9300 non-null   str
 6   url_harmful  6691 non-null   str
dtypes: int64(1), str(6)
memory usage: 508.7 KB

In [31]:
columns_to_drop = ['id','scam_type','language']
spamdf = spamdf.drop(columns_to_drop, axis=1)
spamdf.head()

,text,spam,url_present,url_harmful
0,"Congratulations! You have won PKR 500,000 in H...",spam,no,NaN
1,"Dear Customer, your Meezan Bank account has be...",spam,yes,yes
2,BISP khuskhbri! Aap ko 25000 rupay ki qist mil...,spam,no,NaN
3,Your JazzCash account will be blocked. Please ...,spam,yes,yes
4,Salam! Mujhe ek emergency hai. Mera phone khat...,spam,no,NaN

In [32]:
# now going to drop the url_present and url_harmful colmns also because it does not have such an impact
spamdf = spamdf.drop (['url_present','url_harmful'],axis=1)
spamdf.head()

                                                text  spam
0  Congratulations! You have won PKR 500,000 in H...  spam
1  Dear Customer, your Meezan Bank account has be...  spam
2  BISP khuskhbri! Aap ko 25000 rupay ki qist mil...  spam
3  Your JazzCash account will be blocked. Please ...  spam
4  Salam! Mujhe ek emergency hai. Mera phone khat...  spam

In [33]:
spamdf.head()

                                                text  spam
0  Congratulations! You have won PKR 500,000 in H...  spam
1  Dear Customer, your Meezan Bank account has be...  spam
2  BISP khuskhbri! Aap ko 25000 rupay ki qist mil...  spam
3  Your JazzCash account will be blocked. Please ...  spam
4  Salam! Mujhe ek emergency hai. Mera phone khat...  spam

In [34]:
spamdf.isnull().sum()
spamdf = spamdf.rename(columns={"spam":"is_spam"})
spamdf["is_spam"] = spamdf['is_spam'].map({"spam":1,'ham':0})

In [35]:
# now applying the countvectorizer method to convert the text into numeric data 
from sklearn.feature_extraction.text import CountVectorizer
splitter = CountVectorizer()
input_data = splitter.fit_transform(spamdf.text)

In [36]:
input_df = pd.DataFrame(input_data.toarray(),columns=splitter.get_feature_names_out())
input_df.head()

,00,000,01,02,021,0300,0301,0303,0311,0312,...,ہیلتھ,ہیلپ,ہیک,ہیں,ہے,یا,یوتھ,یوٹیوب,یہ,یہاں
0,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
# now merging both of the dataframe
spamdf= spamdf.reset_index(drop=True)
input_df = input_df.reset_index(drop=True)
spam_final_df = pd.concat([input_df,spamdf], axis=1)
spam_final_df.head()

,00,000,01,02,021,0300,0301,0303,0311,0312,...,ہیک,ہیں,ہے,یا,یوتھ,یوٹیوب,یہ,یہاں,text,is_spam
0,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,"Congratulations! You have won PKR 500,000 in H...",1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"Dear Customer, your Meezan Bank account has be...",1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,BISP khuskhbri! Aap ko 25000 rupay ki qist mil...,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Your JazzCash account will be blocked. Please ...,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Salam! Mujhe ek emergency hai. Mera phone khat...,1

In [38]:
spam_final_df= spam_final_df.drop ('text',axis=1)

In [39]:
spam_final_df.head()

,00,000,01,02,021,0300,0301,0303,0311,0312,...,ہیلپ,ہیک,ہیں,ہے,یا,یوتھ,یوٹیوب,یہ,یہاں,is_spam
0,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [40]:
from sklearn.model_selection import train_test_split
x = spam_final_df.drop('is_spam',axis=1)
y = spam_final_df.is_spam
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [41]:
# now importing the algorthem 
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()

In [42]:
# hypertunning for the model 
from sklearn.model_selection import GridSearchCV
parameters = {
    'alpha': [0.001, 0.01, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10.0],
    'binarize': [0.0, None],
    'fit_prior': [True, False]
    }
detector = GridSearchCV(classifier,parameters)
detector.fit(x_train,y_train)

GridSearchCV(estimator=BernoulliNB(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0,
                                   10.0],
                         'binarize': [0.0, None], 'fit_prior': [True, False]})

In [44]:
training_score = detector.score(x_train,y_train)
testing_score = detector.score(x_test,y_test)
print(f"The training score is : {training_score}\nThe testing score is : {testing_score}")

The training score is : 0.9995967741935484
The testing score is : 0.9967741935483871

In [45]:
# also let see what are the best parameters that are selected 
print (detector.best_params_)

{'alpha': 0.2, 'binarize': None, 'fit_prior': True}